name: CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{github.ref}}

      - run: npm install
      - run: npm test
      - run: npm run build

      - name: Push /docs to gh-pages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "$GITHUB_ACTOR" &&
          git config user.email "${GITHUB_ACTOR}@bots.github.com" &&
          (git branch -D gh-pages || true) &&
          git checkout --orphan gh-pages &&
          git reset --hard &&
          git add docs &&
          git commit -m "new release" &&
          git push -f --set-upstream origin gh-pages
